### ISSUE TITLE
Filter title

### ISSUE THREAD

**Issue by purelines** [suenerds/nova-searchable-belongs-to-filter#1]
Hello, thanks for useful filter!

Please, avoid to change default filter title (you've set "Filter by _attribute_") or add a function to change filter title.

**Comment by thoresuenert** [comment]
@PureLines thanks.

what do you expect for the default filter title?

Novas default strategy is the class name, as follows:
![image-2](https://user-images.githubusercontent.com/382395/70792815-523b2b80-1d9a-11ea-9780-f6939209bc1a.png)

We used the attribute to be able to use multiple filters for the same resource.

You have two options to change the title:

1. Translation helper
```php
  public function name()
    {
        return __('Filter by ' . $this->getFieldAttribute());
    }
```
Use the translation.

2. Extend the class and overwrite the `function name()`


We will think about the right approach to overwrite the title

**Comment by purelines** [comment]
I expect the attribute name without the prefix 'Filter by '.

Original Nova's `name()` function allows to set the title right in a resource.

**Comment by thoresuenert** [comment]
@PureLines please provide a code example for the `name()` setting from the resource.

**Comment by purelines** [comment]
Sure:

```php
    /**
     * Get the filters available for the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function filters(Request $request)
    {
       $myFilter = new Filters\SearchableFilter;
       $myFilter->name = 'My filter title';
       $myFilter->fieldAttribute('owner')->filterBy('owner_id');
       return [
            $myFilter,
       ];
    }
```
Yes, this is not beautiful, but it's possible if you don't override `name()` function.

I think it will be better to add something like this to your filter class:
```php
    /**
     * The displayable name of the filter.
     *
     * @var string
     */
    public $name;

    /**
     * Get the displayable name of the filter.
     *
     * @return string
     */
    public function name()
    {
        return $this->name ?: __('Filter by ' . $this->getFieldAttribute());
    }

    /**
     * Set the displayable name of the filter.
     *
     * @param  string  $value
     * @return \App\Nova\Filters\SearchableFilter
     */
    public function setName($value)
    {
        $this->name = $value;
        return $this;
    }
```

**Comment by cgarofalo** [comment]
I agree with @PureLines. Even better would be to drop the "Filter By", it's redundant, and add PureLines' setName function. Aside from this annoyance, your package works great! Thanks.
