### ISSUE TITLE
How can I customize the data in the drop-down list?

### ISSUE THREAD

**Issue by YarinceP** [suenerds/nova-searchable-belongs-to-filter#10]
Hello, thanks for useful filter!

Please, How can I customize the data in the drop-down list?

**Comment by thoresuenert** [comment]
@YarinceP
Can you provide an example what do you want to customize?

**Comment by YarinceP** [comment]
Of course.
Below is an example image. Where a list of municipalities is shown; Many municipalities belong to a state, so you want to show the municipalities with the name of the state they belong to (Since there are many municipalities with the same name in different states) for example: Acajete belongs to the state of Oaxaca, then in the list I want to show something like this "Acajete - Oaxaca"


![question](https://user-images.githubusercontent.com/28911286/73852563-02566f00-47f5-11ea-922f-68b0c0a32341.png)

To do this I do it manually by making a query, I leave the code below:

![my code municipio](https://user-images.githubusercontent.com/28911286/73853360-59107880-47f6-11ea-95cc-7e7277792eb4.png)

**Comment by YarinceP** [comment]
@thoresuenert Could you help me?

**Comment by thoresuenert** [comment]
@YarinceP I didn't have the time to look deeper into it, but this package is maybe the wrong one for you.

This package ignores the options function and uses a Ajax request to use an existing relation ship.

We make use of the belongsTo functionality which is provided by nova for forms.

**Comment by thoresuenert** [comment]
With this package you should use the following: https://nova.laravel.com/docs/2.0/resources/relationships.html#belongsto

Overwrite this function of the related resource:
```php
/**
 * Get the value that should be displayed to represent the resource.
 *
 * @return string
 */
public function title()
{
    return $this->name;
}
```
