### ISSUE TITLE
moontoast/math is abandoned

### ISSUE THREAD

**Issue by cgarofalo** [suenerds/nova-searchable-belongs-to-filter#4]
```
Installing suenerds/nova-searchable-belongs-to-filter (v1.0.3): Downloading (100%)
Package moontoast/math is abandoned, you should avoid using it. Use brick/math instead.
```

Your package seems to be using an outdated dependancy. Please update it. Thanks.

**Comment by thoresuenert** [comment]
@cgarofalo 
That is misleading the package don't have any dependency beside laravel nova.
And we forget to require Laravel Nova as a dependency ;)
