### ISSUE TITLE
Class 'App\Nova\NovaSearchableBelongsToFilter' not found

### ISSUE THREAD

**Issue by sam-g-roberts** [suenerds/nova-searchable-belongs-to-filter#5]
Hi There.

I think i'm being pretty stupid here but i've copied your code from the example and i cant figure out what should be in the dependency injection at the top of the nova model so that it pulls it into the page correctly. Perhaps this dependancy injection line should be on your example like with other repos? This is the code for my filters.

 /**
* Get the filters available for the resource.
*
* @param  \Illuminate\Http\Request  $request
* @return array
*/
public function filters(Request $request)
{
return [
            new Filters\Status,
            new Filters\ApplicationResponse,
            (new NovaSearchableBelongsToFilter)
                ->fieldAttribute('network')
                ->filterBy('network_id')
        ];

Thanks for your help

Sam

**Comment by thoresuenert** [comment]
@sam-g-roberts no problem I have you covered.

You have to include the filter from the namespace of the package,`Suenerds\NovaSearchableBelongsToFilter` :


```
use Suenerds\NovaSearchableBelongsToFilter\NovaSearchableBelongsToFilter
```
